#!/usr/bin/env bash
# Configures Nginx to include a custom HTTP response header X-Served-By

sudo apt-get update -y
sudo apt-get install -y nginx

server_hostname=$(hostname)

config="server {\n\tlisten 80 default_server;\n\tlisten [::]:80 default_server;\n\troot /var/www/html;\n\tindex index.html index.htm;\n\tserver_name _;\n\tadd_header X-Served-By $server_hostname;\n\tlocation / {\n\t\ttry_files \$uri \$uri/ =404;\n\t}\n}"

echo -e "$config" | sudo tee /etc/nginx/sites-available/default > /dev/null

sudo service nginx restart
