#!/usr/bin/env bash
# Configures Nginx to include a custom HTTP response header

sudo apt-get update
sudo apt-get install -y nginx

HOSTNAME=$(hostname)

sudo sed -i '/add_header X-Served-By/d' /etc/nginx/sites-available/default
sudo sed -i "/listen 80 default_server;/a \\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default

sudo service nginx restart
