#!/usr/bin/env bash
# Installs and configures HAProxy as a load balancer

sudo apt-get update
sudo apt-get install -y haproxy

sudo bash -c 'cat >> /etc/haproxy/haproxy.cfg <<EOF

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server 7057-web-01 3.86.250.240:80 check
    server 7057-web-02 54.152.16.128:80 check
EOF
'

sudo systemctl enable haproxy
sudo systemctl restart haproxy
