#!/usr/bin/env bash
# Installs and configures Nginx web server
apt-get update -y > /dev/null 2>&1
apt-get install nginx -y > /dev/null 2>&1
echo "Holberton School" | tee /var/www/html/index.nginx-debian.html
service nginx restart > /dev/null 2>&1
