#!/usr/bin/env bash
# Installs and configures Nginx web server
apt-get update -y -qq
apt-get install nginx -y -qq
echo "Holberton School" > /var/www/html/index.nginx-debian.html
service nginx restart > /dev/null 2>&1
