#!/usr/bin/env bash
# Installs and configures Nginx web server

sudo apt update -y
sudo apt install nginx -y
echo "Holberton School for the win!" | sudo tee /var/www/html/index.html
sudo service nginx restart
