#!/usr/bin/env bash
# Configures Nginx with a 301 redirect

apt update -y
apt install -y nginx
echo "Holberton School" > /var/www/html/index.html
config="server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;
	location / {
		try_files \$uri \$uri/ =404;
	}
	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}
}
"
echo "$config" > /etc/nginx/sites-available/default
service nginx restart
