#!/usr/bin/env bash
# Configures Nginx with a 301 redirect

sudo apt-get update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /var/www/html/index.html
new_string="server_name _;\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
sudo sed -i "s|server_name _;|$new_string|" /etc/nginx/sites-available/default
sudo service nginx restart
