#!/usr/bin/env bash
# Configures Nginx with a custom 404 page

sudo apt-get update -y
sudo apt-get install -y nginx
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
sudo sed -i "s|server_name _;|server_name _;\n\terror_page 404 /404.html;|" /etc/nginx/sites-available/default
sudo service nginx restart
