#!/usr/bin/env bash
# Configures Nginx with a custom 404 page
apt-get update
apt-get install -y nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
sed -i '37i\        location /redirect_me {\n                return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n        }' /etc/nginx/sites-available/default
sed -i '37i\        error_page 404 /404.html;\n        location = /404.html {\n                internal;\n        }' /etc/nginx/sites-available/default
service nginx restart
