#!/usr/bin/env bash
# Configures Nginx with a custom 404 page
apt-get update -y > /dev/null 2>&1
apt-get install nginx -y > /dev/null 2>&1
echo "Holberton School" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" | tee /var/www/html/404.html
sed -i '/server_name _;/a \\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default
sed -i '/server_name _;/a \\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\tinternal;\n\t}' /etc/nginx/sites-available/default
service nginx restart > /dev/null 2>&1
